New translation to spanish language.
zonemaster/zonemaster-gui pull request #272
Opened 2021-11-02 20:16 UTC by huguei

Here are the new two files es.json and gui-faq-es.md. Please I ask you for the rest of steps (typescripts and other json files).

2021-11-04 14:15 UTC, blacksponge commented
Hi, thanks for the translation!
The steps are those described in the [translation guide](https://github.com/zonemaster/zonemaster-gui/blob/develop/docs/TranslationGuide.md), in you case they should be the following:
* Update package.json and add `es` to the language list
https://github.com/zonemaster/zonemaster-gui/blob/d5ea51931d200f0b78da9f1c37948819fe313684/package.json#L14
* Add `import 'moment/locale/es';` after the other `import 'moment/locale/*'` in app.module.ts
https://github.com/zonemaster/zonemaster-gui/blob/d5ea51931d200f0b78da9f1c37948819fe313684/src/app/app.module.ts#L35-L40
* Add the language name (`'es': 'Español',` if I am not making any mistakes) in common.ts 
https://github.com/zonemaster/zonemaster-gui/blob/d5ea51931d200f0b78da9f1c37948819fe313684/src/environments/common.ts#L8-L15
* Also in common.ts, add the language code to the enabled language list
https://github.com/zonemaster/zonemaster-gui/blob/d5ea51931d200f0b78da9f1c37948819fe313684/src/environments/common.ts#L16
* Update the example configuration file to add the language code to the enabled language list
https://github.com/zonemaster/zonemaster-gui/blob/d5ea51931d200f0b78da9f1c37948819fe313684/src/assets/app.config.sample.json#L5
* Create the file `e2e/FR05-es.e2e-spec.ts` with the following content
```ts
import { by, browser, element, ExpectedConditions } from 'protractor';

import { Utils } from './utils/app.utils';

describe('Zonemaster test FR05-es - [Supports Spanish language]', () => {

  const utils = new Utils();

  beforeAll(async () => {
    await utils.goToHome();
  });

  it('should have French language button', () => {
    expect(element(by.xpath('//a[@lang="es"]')).isPresent()).toBe(true);
  });

  it('should switch to French', async () => {
    await utils.setLang('fr');
    await browser.wait(() => ExpectedConditions.presenceOf(element(by.xpath('//h1[.="Nombre de dominio"]'))), 5 * 1000);
    const selectedLang = element.all(by.css('nav div.lang a.selected'));
    expect(selectedLang.count()).toBe(1);
    expect(selectedLang.first().getAttribute('lang')).toBe('es');
  });
});
```
* Update the default languages in the documentation file Configuration.md
https://github.com/zonemaster/zonemaster-gui/blob/d5ea51931d200f0b78da9f1c37948819fe313684/docs/Configuration.md#L25-L26
* Add Spanish to the supported languages in TranslationGuide.md
https://github.com/zonemaster/zonemaster-gui/blob/d5ea51931d200f0b78da9f1c37948819fe313684/docs/TranslationGuide.md#L20-L25

Feel free to ask for clarification if I wasn't clear somewhere.

2021-11-04 16:18 UTC, huguei commented
Thanks @blacksponge . In private talks with @matsduf he offered to take care of this steps. I see no problem to do it myself, but I'll wait him to not step into each other.

2021-11-04 19:19 UTC, huguei commented
Done. I've just added to the PR the typescript, test and docs modifications.

2021-11-05 07:56 UTC, matsduf commented on src/environments/common.ts
> +  enabledLanguages: [ 'da', 'en', 'fi', 'fr', 'nb', 'sv', 'es' ],
Please put "es" between "en" and "fi" (alphabetical order)

2021-11-05 08:36 UTC, matsduf requested changes
Besides the non-alphabetical order in common.ts I found yet another file that needs addition of "es", i.e. `angular.json`
```
            "allowedCommonJsDependencies": [
              "moment/locale/da",
              "moment/locale/fi",
              "moment/locale/fr",
              "moment/locale/nb",
              "moment/locale/sv"
            ],
```
The file is not documented in the translation guide so I will update there.

Besides that it looks fine. Good and quick job!

2021-11-05 12:08 UTC, huguei commented
Last requested changes were done.

2021-11-05 12:18 UTC, matsduf commented
@huguei, thanks. Due to another pull request being merged to the develop branch there is a technical conflict. Either you can resolve it or I can do that.

2021-11-05 12:27 UTC, blacksponge commented on src/assets/app.config.sample.json
>      "logo": "assets/images/zonemaster_logo_2021_color.png"
There is a missing comma at the end of this line

2021-11-05 13:23 UTC, matsduf commented
@blacksponge, the Travis error does not look like it is PR related. Is it?

2021-11-05 13:25 UTC, blacksponge commented
No, it is caused by some rate limiting on Github API when updating the webdriver. I have run the test locally and they pass successfully.

> [12:32:40] I/config_source - curl -o/home/travis/build/zonemaster/zonemaster-gui/node_modules/webdriver-manager/selenium/gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
> (node:6449) UnhandledPromiseRejectionWarning: Error: Failed to make Github request, rate limit reached.

2021-11-05 13:40 UTC, matsduf commented
> No, it is caused by some rate limiting on Github API when updating the webdriver.

Github? Not Travis?

2021-11-05 13:43 UTC, blacksponge commented
The github API is called from travis when updating the webdriver at this step of the CI script
https://github.com/zonemaster/zonemaster-gui/blob/10a273f6d8a5ed02b6ea31cd335c555b672ef885/.travis.yml#L14

2021-11-05 14:10 UTC, blacksponge commented
I have restarted the tests, it works now.

2021-11-05 14:23 UTC, matsduf commented
We defer merging until the Spanish translation has been merged in Engine and configuration has been merged in Backend.

2021-11-11 16:53 UTC, mattias-p commented
@matsduf Are there any more changes that need to be made to this PR before it can be merged? You're still marked as "Request changes".

2021-11-11 16:58 UTC, matsduf commented
> @matsduf Are there any more changes that need to be made to this PR before it can be merged? You're still marked as "Request changes".

No, but we should start with Engine.

2021-12-06 12:49 UTC, matsduf approved these changes

2021-12-17 14:30 UTC, merged