Moves HTML anchor into header and creates valid HTML
zonemaster/zonemaster-gui pull request #407
Opened 2023-05-05 09:25 UTC by matsduf

## Purpose

HTML files are created from markdown files. The current markdown code puts the anchor in a paragraph before the headline the link should link to. The solution does not create valid HTML. This PR resolves the issue.

## Changes

All FAQ files in `docs/FAQ/gui-faq-*.md`, but no change of content.

## How to test this PR

Links in table of contents should go to the right question.

2023-05-05 12:00 UTC, marc-vanderwal submitted a review, later dismissed
Looks good to me.

2023-05-09 07:18 UTC, blacksponge commented
Please update the translation guide https://github.com/zonemaster/zonemaster-gui/blob/master/docs/TranslationGuide.md#gui-faq-langmd

And the style of the FAQ https://github.com/zonemaster/zonemaster-gui/blob/master/src/app/components/faq/faq.component.css#L1

2023-05-09 08:54 UTC, blacksponge commented
`faq.component.css` needs to be updated as well, specifically the `ngAfterViewChecked` method,

```js
  ngAfterViewChecked(): void {
    if (!this.fragment) {
      return
    }

    const faqEntry = document.getElementById(this.fragment);
    if (faqEntry !== null) {
      faqEntry.scrollIntoView();
      this.fragment = '';
    }
  }
```

While testing I noticed a strange behaviour when clicking on a link for the first time on Firefox, the browser does not  scroll down all the way to the FAQ entry but stops with a warning in the console saying `Scroll anchoring was disabled in a scroll container because of too many consecutive adjustments`. This seems to be related to (scroll anchoring)[https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor/Guide_to_scroll_anchoring].  Adding the following into the component style fixes the issue.
```css
.faq {
  overflow-anchor: none;
}
```

2023-05-09 16:22 UTC, matsduf commented
@blacksponge  and @rhedman, as far as I understand, the old content of src/app/components/faq/faq.component.css is not needed anymore.

2023-05-09 16:39 UTC, blacksponge commented
> as far as I understand, the old content of src/app/components/faq/faq.component.css is not needed anymore.

It is, the selector should be updated to `span[id^=q] ` instead of `a[name^=q] `.
This rule is to offset the scroll to avoid having the entry title hidden by the navigation menu at the top.

2023-05-09 16:41 UTC, blacksponge commented on src/app/components/faq/faq.component.ts
> +Aimport { Component, OnInit, AfterViewChecked, OnDestroy, Inject, LOCALE_ID } from '@angular/core';
Extra `A`.

2023-05-09 21:11 UTC, matsduf commented
> > as far as I understand, the old content of src/app/components/faq/faq.component.css is not needed anymore.
> 
> It is, the selector should be updated to `span[id^=q] ` instead of `a[name^=q] `. This rule is to offset the scroll to avoid having the entry title hidden by the navigation menu at the top.

I will put it back, updated.

2023-05-09 21:11 UTC, matsduf commented on src/app/components/faq/faq.component.ts
> +Aimport { Component, OnInit, AfterViewChecked, OnDestroy, Inject, LOCALE_ID } from '@angular/core';
Fixed in conflict resolution.

2023-05-10 05:45 UTC, rhedman commented
@blacksponge @matsduf 
Could we create a setting in the config that completely turns off all styles? Something like: `globalStyles: false`. I'm implementing a new design and it's a hassle to always have to write CSS-selectors that overrides the default CSS.

2023-05-10 15:44 UTC, matsduf commented
@blacksponge and @rhedman, please rereview.

2023-05-11 06:01 UTC, rhedman requested changes
Change this selector: :host ::ng-deep span[id^=q]
Into this .faq span[id^=q]

2023-05-11 07:18 UTC, matsduf commented on src/app/components/faq/faq.component.css
> +:host ::ng-deep span[id^=q] {
I have updated the CSS file.

2023-05-11 07:23 UTC, rhedman approved these changes

2023-05-11 07:49 UTC, blacksponge approved these changes

2023-05-11 08:10 UTC, merged

2023-05-31 14:43 UTC, pnax commented
### v2023.1 release testing

Clicking on the links in the FAQ scroll to the right section. The section title is properly displayed at the top of the viewport, just below the header.